routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(array('middleware' => 'auth'), function()
{
Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('admin', 'AdminController');

Route::resource('kriteria', 'KriteriaController');
Route::resource('sub_kriteria', 'SubKriteriaController',
                ['only' => ['show', 'destroy', 'store', 'update']]);
Route::get('/sub_kriteria/{kode_kriteria}/create','SubKriteriaController@create')->name('sub_kriteria.create');
Route::get('/sub_kriteria/{kode_kriteria}/edit','SubKriteriaController@edit')->name('sub_kriteria.edit');
Route::get('/hasil/{jurusan}/{kelas}','HasilController@hasil')->name('hasil.index');
Route::resource('alternatif', 'AlternatifController');
Route::resource('bobot_kriteria', 'BobotKriteriaController');
Route::resource('bobot_sub_kriteria', 'BobotSubKriteriaController');

Route::get('/hasil', function () {
    return view('perhitungan.jurusan');
});
Route::get('/hasil/{jurusan}','HasilController@kelas')->name('hasil.kelas');
Route::get('/hasil/{jurusan}/kelas', function () {
    return view('perhitungan.kelas');
});
});

app/Alternatif.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
class Alternatif extends Model
{
    protected $fillable = [
        'nisn', 'nama'
    ];
    protected $table = "alternatif";
    protected $primaryKey = 'nisn';
    public $incrementing = false;
    public function nilai_alternatif()
    {
        return $this->hasMany('App\NilaiAlternatif', 'nisn', 'nisn');
    }
}

app/Http/Controllers/AlternatifController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Alternatif;
use App\NilaiAlternatif;
use App\Kriteria;

class AlternatifController extends Controller
{
    public function index(){
        $kriteria = Kriteria::all();
        $data = Alternatif::all();
        return view('alternatif.alternatif')->with('data', $data);
    }
    public function show($id){
        $data = Alternatif::with('nilai_alternatif.sub_kriteria.kriteria')->where('nisn', $id)->first();
        if($data){
            return view('alternatif.nilai_alternatif')->with('data', $data);
        }
    }
    public function create(){
        $kriteria = Kriteria::with('sub_kriteria')->get();
        return view('alternatif.tambah_alternatif')->with('kriteria', $kriteria);
    }
    public function store(Request $request){
        $this->validate($request,[
            'nisn' => 'required|unique:alternatif',
            'nama' => 'required'
         ]);
        $data = new Alternatif;
        $data->nisn = request('nisn');
        $data->nama = request('nama');
        $data->save();
        foreach (request('nilai') as $key => $value) {
            $data_nilai = new NilaiAlternatif;
            $data_nilai->nisn = request('nisn');
            $data_nilai->kode_sub_kriteria = $value;
            $data_nilai->save();
        }
        return redirect()->route('alternatif.index');
    }
    public function edit($id){
        $alternatif = Alternatif::with('nilai_alternatif')->where('nisn', $id)->first();
        $data = Kriteria::with('sub_kriteria')->get();
        if($data){
            return view('alternatif.edit_alternatif')->with(['data' => $data, 'alternatif' => $alternatif]);
        }
        return redirect()->route('alternatif.index');
    }
    public function update(Request $request, $id){
        $this->validate($request,[
            'nisn' => 'required',
            'nama' => 'required'
         ]);
        $data = Alternatif::where('nisn', request('nisn'))->first();
        $data->nisn = request('nisn');
        $data->nama = request('nama');
        $data->save();
        $delete =  NilaiAlternatif::where('nisn', request('nisn'))->delete();
        foreach (request('nilai') as $key => $value) {
            $data_nilai = new NilaiAlternatif;
            $data_nilai->nisn = request('nisn');
            $data_nilai->kode_sub_kriteria = $value;
            $data_nilai->save();
        }
        return redirect()->route('alternatif.index');
    }
    public function destroy($id){
        $data = Alternatif::where('nisn', $id)->first();
        if($data){
            $data->delete();
        }
        return redirect()->route('alternatif.index');
    }
}

resources/views/alternatif/alternatif.blade.php
@extends('layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">ALTERNATIF</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active">Alternatif</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
    <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
              <table id="data-admin" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>NO</th>
                  <th>NAMA SISWA</th>
                  <th>NISN</th>
                  <th>NILAI ALTERNATIF</th>
                  <th>AKSI</th>
                </tr>
                </thead>
                <tbody>
                  @foreach($data as $sis)
                <tr>
                  <td>{{$loop->iteration}}</td>
                  <td>{{$sis->nama}}</td>
                  <td>{{$sis->nisn}}</td>
                  <td>
                    <a href="/alternatif/{{$sis->nisn}}">
                      <span class="badge badge-secondary" data-toggle="tooltip" data-placement="top" title="Ubah">Lihat Nilai Alternatif</span>
                    </a>
                  </td>
                  <td>
                    <a href="/alternatif/{{$sis->nisn}}/edit">
                      <span class="btn badge badge-secondary" data-toggle="tooltip" data-placement="top" title="Ubah"><i class="fa fa-pencil"></i></span>
                    </a>                    
                    <span class="btn badge badge-danger" onclick="event.preventDefault(); document.getElementById('delete-kriteria').submit();" data-toggle="tooltip" data-placement="top" title="Hapus"><i class="fa fa-trash"></i></span>
                  </td>
                  
                  <form id="delete-kriteria" action="/alternatif/{{$sis->nisn}}" method="post" style="display: none;">
                    @method('DELETE')
                    @csrf
                  </form>
                </tr>
                @endforeach
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
    </section>
@include ('includes.script')
<script type="text/javascript">
$(document).ready(function(){
    // Append all paragraphs
    $("#data-admin_length").append('<a  href="{{ route('alternatif.create') }}"> <button type="button" class="btn btn-outline-primary ml-3">Tambah</button></a>');
});
</script>
@endsection

resources/views/alternatif/edit_alternatif.blade.php
@extends('layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">TAMBAH ALTERNATIF</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active">Alternatif</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <section class="content">
      <div class="card">
      @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
      @endif
      <!-- /.card-header -->
      <div class="card-body">
        <form role="form" method="post" action="/alternatif/{{$alternatif->nisn}}">
        @csrf
        @method('PATCH')
        <div class="row">
          <div class="col-md-6">
            <div class="card-body">
              <div class="form-group">
                <label for="exampleInputEmail1">NISN</label>
                <input type="text" class="form-control" value="{{$alternatif->nisn}}" name="nisn" id="exampleInputEmail1" placeholder="kode nisn siswa">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Nama Siswa</label>
                <input type="text" class="form-control" value="{{$alternatif->nama}}" name="nama" id="exampleInputPassword1" placeholder="nama">
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card-body">
              @foreach($data as $krit)
              <div class="form-group">
                <label for="exampleInputEmail1">Bagaimana {{$krit->nama}} siswa ini ?</label>
                <select class="form-control" name="nilai[{{$krit->kode}}]">
                  @foreach($krit->sub_kriteria as $sub)
                      <option value="{{$sub->kode}}"
                      @foreach($alternatif->nilai_alternatif as $nil)
                      @if ($nil->kode_sub_kriteria == $sub->kode))
                          selected="selected"
                      @endif
                      @endforeach
                      >{{$sub->nama}}</option>
                  @endforeach
                </select>
              </div>
              @endforeach
            </div>
          </div>
        </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-primary float-right">Tambah</button>
          </div>
        </form>
      </div>
      </div>
    </section>
@include ('includes.script')
@endsection

resources/views/alternatif/nilai_alternatif.blade.php
@extends('layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">ALTERNATIF</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active">Alternatif</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
    <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
              <div class="row">
                <div class="col-md-6 col-sm-12">
                  <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                      <th>NISN</th>
                      <th>NAMA</th>
                    </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>{{$data->nisn}}</td>
                        <td>{{$data->nama}}</td>
                        </form>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div class="col-md-6 col-sm-12">
                  <table id="data-admin" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                      <th>NO</th>
                      <th>NAMA KRITERIA</th>
                      <th>NILAI</th>
                    </tr>
                    </thead>
                    <tbody>
                      @foreach($data->nilai_alternatif as $nil)
                      <tr>
                        <td>{{$loop->iteration}}</td>
                        <td>{{$nil->sub_kriteria->kriteria->nama}}</td>
                        <td>{{$nil->sub_kriteria->nama}}</td>
                        </form>
                      </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <!-- /.card-body -->
          </div>
    </section>
@include ('includes.script')
<script type="text/javascript">
$(document).ready(function(){
    // Append all paragraphs
    $("#data-admin_length").append('<a  href="/alternatif/{{$data->nisn}}/edit" <button type="button" class="btn btn-outline-primary ml-3">UBAH</button></a>');
});
</script>
@endsection

resources/views/alternatif/tambah_alternatif.blade.php
@extends('layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">TAMBAH ALTERNATIF</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active">Alternatif</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <section class="content">
      <div class="card">
      @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
      @endif
      <!-- /.card-header -->
      <div class="card-body">
        <form role="form" method="post" action="{{ route('alternatif.store') }}">
        @csrf
        <div class="row">
          <div class="col-md-6">
            <div class="card-body">
              <div class="form-group">
                <label for="exampleInputEmail1">NISN</label>
                <input type="text" class="form-control" name="nisn" id="exampleInputEmail1" placeholder="kode nisn siswa">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Nama Siswa</label>
                <input type="text" class="form-control" name="nama" id="exampleInputPassword1" placeholder="nama">
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card-body">
              @foreach($kriteria as $krit)
              <div class="form-group">
                <label for="exampleInputEmail1">Bagaimana {{$krit->nama}} siswa ini ?</label>
                <select class="form-control" name="nilai[{{$krit->kode}}]">
                  @foreach($krit->sub_kriteria as $sub)
                      <option value="{{$sub->kode}}">{{$sub->nama}}</option>
                  @endforeach
                </select>
              </div>
              @endforeach
            </div>
          </div>
        </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-primary float-right">Tambah</button>
          </div>
        </form>
      </div>
      </div>
    </section>
@include ('includes.script')
@endsection