routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(array('middleware' => 'auth'), function()
{
Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('admin', 'AdminController');

Route::resource('kriteria', 'KriteriaController');
Route::resource('sub_kriteria', 'SubKriteriaController',
                ['only' => ['show', 'destroy', 'store', 'update']]);
Route::get('/sub_kriteria/{kode_kriteria}/create','SubKriteriaController@create')->name('sub_kriteria.create');
Route::get('/sub_kriteria/{kode_kriteria}/edit','SubKriteriaController@edit')->name('sub_kriteria.edit');
Route::get('/hasil/{jurusan}/{kelas}','HasilController@hasil')->name('hasil.index');
Route::resource('alternatif', 'AlternatifController');
Route::resource('bobot_kriteria', 'BobotKriteriaController');
Route::resource('bobot_sub_kriteria', 'BobotSubKriteriaController');

Route::get('/hasil', function () {
    return view('perhitungan.jurusan');
});
Route::get('/hasil/{jurusan}','HasilController@kelas')->name('hasil.kelas');
Route::get('/hasil/{jurusan}/kelas', function () {
    return view('perhitungan.kelas');
});
});

resources/views/admin/admin.blade.php
@extends('layouts.app_noscript')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">ADMIN / GURU</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active">Admin Guru</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
    <div class="card">
      @if(session('success'))
      <span class="alert alert-success" role="alert">
          <strong>{{ session('success') }}</strong>
      </span>
      @endif
      @if(session('error'))
      <span class="alert alert-danger" role="alert">
          <strong>{{ session('error') }}</strong>
      </span>
      @endif
            <!-- /.card-header -->
            <div class="card-body">
              <table id="data-admin" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>NO</th>
                  <th>USERNAME</th>
                  <th>NAMA</th>
                  <th>E-MAIL</th>
                  <th>NO. TELP</th>
                  <th>AKSI</th>
                </tr>
                </thead>
                <tbody>
                  @foreach($data as $admin)
                <tr>
                  <td>{{$loop->iteration}}</td>
                  <td>{{$admin->username}}</td>
                  <td>{{$admin->name}}</td>
                  <td>{{$admin->email}}</td>
                  <td>{{$admin->no_telp}}</td>
                  <td>
                    <span onclick="event.preventDefault(); document.getElementById('delete-admin{{$admin->id}}').submit();"  class="badge badge-danger" data-toggle="tooltip" data-placement="top" title="Hapus"><i class="fa fa-trash"></i></span>
                  </td>
                  <form id="delete-admin{{$admin->id}}" action="/admin/{{$admin->id}}" method="post" style="display: none;">
                    @method('DELETE')
                    @csrf
                  </form>
                </tr>
                @endforeach
                </tbody>
              </table>
            </div>
          </div>
    </section>
@include ('includes.script')
<script type="text/javascript">
$(document).ready(function(){
    // Append all paragraphs
    $("#data-admin_length").append('<a href="/admin/create"><button type="button" class="btn btn-outline-primary ml-3">Tambah</button></a>');
});
</script>
@endsection

resources/views/admin/create.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">TAMBAH ADMIN</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item active">Tambah Admin</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="card">
    @if ($errors->any())
    <div class="alert alert-danger">
      <ul>
        @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
    @endif
    <!-- /.card-header -->
    <div class="card-body">
      <form role="form" method="post" action="{{ route('admin.store') }}">
        @csrf
        <div class="card-body">
          <div class="form-group">
            <label for="exampleInputEmail1">Nama</label>
            <input type="text" class="form-control" name="name" id="nama" placeholder="nama">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Email</label>
            <input type="email" class="form-control" name="email" id="email" placeholder="email">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">No Telp</label>
            <input type="text" class="form-control" name="no_telp" id="no_telp" placeholder="nomor telpon">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">password</label>
            <input type="password" class="form-control" name="password" id="password" placeholder="password">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">ulangi password</label>
            <input type="password" class="form-control" name="password_confirm" id="password" placeholder="ulangi password">
          </div>
        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>
    </div>
    <!-- /.card-body -->
  </div>
</section>
@include ('includes.script')
@endsection