routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(array('middleware' => 'auth'), function()
{
Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('admin', 'AdminController');

Route::resource('kriteria', 'KriteriaController');
Route::resource('sub_kriteria', 'SubKriteriaController',
                ['only' => ['show', 'destroy', 'store', 'update']]);
Route::get('/sub_kriteria/{kode_kriteria}/create','SubKriteriaController@create')->name('sub_kriteria.create');
Route::get('/sub_kriteria/{kode_kriteria}/edit','SubKriteriaController@edit')->name('sub_kriteria.edit');
Route::get('/hasil/{jurusan}/{kelas}','HasilController@hasil')->name('hasil.index');
Route::resource('alternatif', 'AlternatifController');
Route::resource('bobot_kriteria', 'BobotKriteriaController');
Route::resource('bobot_sub_kriteria', 'BobotSubKriteriaController');

Route::get('/hasil', function () {
    return view('perhitungan.jurusan');
});
Route::get('/hasil/{jurusan}','HasilController@kelas')->name('hasil.kelas');
Route::get('/hasil/{jurusan}/kelas', function () {
    return view('perhitungan.kelas');
});
});

app/SubKriteria.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
class SubKriteria extends Model
{
    protected $fillable = [
        'kode', 'nama'
    ];
    protected $table = "sub_kriteria";
    protected $primaryKey = 'kode';
    public $incrementing = false;
    public $timestamps = false;
    public function kriteria()
    {
        return $this->belongsTo('App\Kriteria', 'kode_kriteria', 'kode');
    }
}

app/Http/Controllers/SubKriteriaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Kriteria;
use App\SubKriteria;

class SubKriteriaController extends Controller
{
    public function show($id){
        $data = Kriteria::with('sub_kriteria')->where('kode', $id)->first();
        return view('sub_kriteria.sub_kriteria')->with('data', $data);
    }
    public function create($id){
        $data = Kriteria::where('kode', $id)->first();
        if($data){
            return view('sub_kriteria.tambah_sub_kriteria')->with('data', $data);
        }
        return redirect()->route('kriteria.index');
    }
    public function store(Request $request){
        $this->validate($request,[
            'kode' => 'required|unique:sub_kriteria',
            'kode_kriteria' => 'required|exists:kriteria,kode',
            'nama' => 'required',
            'parameter' => 'required'
         ]);
        $data = new SubKriteria;
        $data->kode_kriteria = request('kode_kriteria');
        $data->kode = request('kode');
        $data->nama = request('nama');
        $data->parameter = request('parameter');
        $data->save();
        return redirect('/sub_kriteria/'.request('kode_kriteria'));
    }
    public function edit($id){
        $data = SubKriteria::where('kode', $id)->first();
        if($data){
            return view('sub_kriteria.edit_sub_kriteria')->with('data', $data);
        }
        return redirect()->route('sub_kriteria.index');
    }
    public function update(Request $request, $id){
        $this->validate($request,[
            'kode' => 'unique:sub_kriteria,kode,'. $id.',kode',
            'nama' => 'required',
            'parameter' => 'required',
         ]);
        $data = SubKriteria::where('kode', $id)->first();
        if($data){
            $data->kode = request('kode');
            $data->nama = request('nama');
            $data->parameter = request('parameter');
            $data->save();
        }
        return redirect('/sub_kriteria/'.$data->kode_kriteria);
    }
    public function destroy($id){
        $data = SubKriteria::where('kode', $id)->first();
        if($data){
            $data->delete();
        }
        return redirect('/sub_kriteria/'.$data->kode_kriteria);
    }
}

resources/views/sub_kriteria/edit_sub_kriteria.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
    <div class="col-sm-6">
        <h1 class="m-0 text-dark">Sub Kriteria</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item"><a href="/kriteria">Kriteria</a></li>
          <li class="breadcrumb-item"><a href="/sub_kriteria/{{$data->kode_kriteria}}">{{$data->kode_kriteria}}</a></li>
          <li class="breadcrumb-item active">{{$data->nama}}</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->
<section class="content">
  <div class="card">
    @if ($errors->any())
    <div class="alert alert-danger">
      <ul>
          @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
          @endforeach
      </ul>
    </div>
    @endif
    <!-- /.card-header -->
    <div class="card-body">
      <form role="form" method="post" action="{{ route('sub_kriteria.update', $data->kode) }}">
      @csrf
      @method('PATCH')
        <div class="card-body">
          <div class="form-group">
            <label>Kode Kriteria</label>
            <input type="text" class="form-control" name="kode" value="{{$data->kode}}" placeholder="kode">
          </div>
          <div class="form-group">
            <label>Nama Kriteria</label>
            <input type="text" class="form-control" name="nama" value="{{$data->nama}}" placeholder="nama">
          </div>
          <div class="form-group">
            <label>Parameter</label>
            <input type="text" class="form-control" name="parameter" placeholder="0 - 30 / 31 - 60 / 61 - 100">
          </div>
        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Ubah</button>
        </div>
      </form>
    </div>
    <!-- /.card-body -->
  </div>
</section>
@include ('includes.script')
@endsection

resources/views/sub_kriteria/sub_kriteria.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Sub Kriteria <span class="badge badge-secondary" data-toggle="tooltip" data-placement="top" title="Ubah">{{$data->nama}}</span></h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item"><a href="/kriteria">Kriteria</a></li>
          <li class="breadcrumb-item active">{{$data->nama}}</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="card">
    <!-- /.card-header -->
    <div class="card-body">
      <table id="data-admin" class="table table-bordered table-striped">
        <thead>
        <tr>
          <th>NO</th>
          <th>KODE</th>
          <th>NAMA</th>
          <th>PARAMETER</th>
          <th>AKSI</th>
        </tr>
        </thead>
        <tbody>
          @foreach($data->sub_kriteria as $krit)
        <tr>
          <td>{{$loop->iteration}}</td>
          <td>{{$krit->kode}}</td>
          <td>{{$krit->nama}}</td>
          <td>{{$krit->parameter}}</td>
          <td>
            <a href="/sub_kriteria/{{$krit->kode}}/edit">
              <span class="btn badge badge-secondary" data-toggle="tooltip" data-placement="top" title="Ubah"><i class="fa fa-pencil"></i></span>
            </a>                    
            <span class="btn badge badge-danger" onclick="event.preventDefault(); document.getElementById('delete-kriteria{{$krit->kode}}').submit();" data-toggle="tooltip" data-placement="top" title="Hapus"><i class="fa fa-trash"></i></span>
          </td>
          
          <form id='delete-kriteria{{$krit->kode}}' action="/sub_kriteria/{{$krit->kode}}" method="post" style="display: none;">
            @method('DELETE')
            @csrf
          </form>
        </tr>
        @endforeach
        </tbody>
      </table>
    </div>
    <!-- /.card-body -->
  </div>
</section>
@include ('includes.script')
<script type="text/javascript">
$(document).ready(function(){
    // Append all paragraphs
    $("#data-admin_length").append('<a  href="{{ route('sub_kriteria.create', $data->kode) }}"> <button type="button" class="btn btn-outline-primary ml-3">Tambah</button></a>');
});
</script>
@endsection

resources/views/sub_kriteria/tambah_sub_kriteria.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
    <div class="col-sm-6">
        <h1 class="m-0 text-dark">Tambah Sub Kriteria <span class="badge badge-secondary" data-toggle="tooltip" data-placement="top" title="Ubah">{{$data->nama}}</span></h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item"><a href="/kriteria">Kriteria</a></li>
          <li class="breadcrumb-item active">{{$data->nama}}</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="card">
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <!-- /.card-header -->
    <div class="card-body">
      <form role="form" method="post" action="{{ route('sub_kriteria.store') }}">
      @csrf
        <div class="card-body">
          <div class="form-group">
          <div class="form-group">
            <label for="exampleInputEmail1">Kriteria</label>
              <input type="text" class="form-control" value="{{$data->nama}}" disabled id="exampleInputEmail1" placeholder="kode">
              <input type="hidden" class="form-control" value="{{$data->kode}}" name="kode_kriteria" id="exampleInputEmail1" placeholder="kode">
          </div>
            <label for="exampleInputEmail1">Kode Sub Kriteria</label>
            <input type="text" class="form-control" name="kode" id="exampleInputEmail1" placeholder="kode">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Nama Kriteria</label>
            <input type="text" class="form-control" name="nama" id="exampleInputPassword1" placeholder="nama">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Parameter</label>
            <input type="text" class="form-control" name="parameter" id="exampleInputPassword1" placeholder="0 - 30 / 31 - 60 / 61 - 100">
          </div>
        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Tambah</button>
        </div>
      </form>
    </div>
    <!-- /.card-body -->
  </div>
</section>
@include ('includes.script')
@endsection