routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(array('middleware' => 'auth'), function()
{
Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('admin', 'AdminController');

Route::resource('kriteria', 'KriteriaController');
Route::resource('sub_kriteria', 'SubKriteriaController',
                ['only' => ['show', 'destroy', 'store', 'update']]);
Route::get('/sub_kriteria/{kode_kriteria}/create','SubKriteriaController@create')->name('sub_kriteria.create');
Route::get('/sub_kriteria/{kode_kriteria}/edit','SubKriteriaController@edit')->name('sub_kriteria.edit');
Route::get('/hasil/{jurusan}/{kelas}','HasilController@hasil')->name('hasil.index');
Route::resource('alternatif', 'AlternatifController');
Route::resource('bobot_kriteria', 'BobotKriteriaController');
Route::resource('bobot_sub_kriteria', 'BobotSubKriteriaController');

Route::get('/hasil', function () {
    return view('perhitungan.jurusan');
});
Route::get('/hasil/{jurusan}','HasilController@kelas')->name('hasil.kelas');
Route::get('/hasil/{jurusan}/kelas', function () {
    return view('perhitungan.kelas');
});
});

app/Kriteria.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
class Kriteria extends Model
{
    protected $fillable = [
        'kode', 'nama'
    ];
    protected $table = "kriteria";
    protected $primaryKey = 'kode';
    public $incrementing = false;
    public function sub_kriteria()
    {
        return $this->hasMany('App\SubKriteria', 'kode_kriteria', 'kode');
    }
    public function bobot_kriteria()
    {
        return $this->hasMany('App\BobotKriteria', 'kode_kriteria_1', 'kode');
    }
}

app/Http/Controllers/KriteriaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Kriteria;

class KriteriaController extends Controller
{
    public function index(){
        $data = Kriteria::all();
        return view('kriteria.kriteria')->with('data', $data);
    }
    public function create(){
        return view('kriteria.tambah_kriteria');
    }
    public function store(Request $request){
        $this->validate($request,[
            'kode' => 'required|unique:kriteria',
            'nama' => 'required'
         ]);
        $data = new Kriteria;
        $data->kode = request('kode');
        $data->nama = request('nama');
        $data->save();
        return redirect()->route('kriteria.index');
    }
    public function edit($id){
        $data = Kriteria::where('kode', $id)->first();
        if($data){
            return view('kriteria.edit_kriteria')->with('data', $data);
        }
        return redirect()->route('kriteria.index');
    }
    public function update(Request $request, $id){
        $this->validate($request,[
            'kode' => 'required',
            'nama' => 'required'
         ]);
        $data = Kriteria::where('kode', $id)->first();
        if($data){
            $data->kode = request('kode');
            $data->nama = request('nama');
            $data->save();
        }
        return redirect()->route('kriteria.index');
    }
    public function destroy($id){
        $data = Kriteria::where('kode', $id)->first();
        if($data){
            $data->delete();
        }
        return redirect()->route('kriteria.index');
    }
}

resources/views/kriteria/edit_kriteria.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">ADMIN / GURU</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item active">ADMIN / GURU</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="card">
  @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
  @endif
    <!-- /.card-header -->
    <div class="card-body">
      <form role="form" method="post" action="{{ route('kriteria.update', $data->kode) }}">
      @csrf
      @method('PATCH')
        <div class="card-body">
          <div class="form-group">
            <label for="exampleInputEmail1">Kode Kriteria</label>
            <input type="text" class="form-control" name="kode" value="{{$data->kode}}" id="exampleInputEmail1" placeholder="kode">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Nama Kriteria</label>
            <input type="text" class="form-control" name="nama" value="{{$data->nama}}" id="exampleInputPassword1" placeholder="nama">
          </div>
        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Ubah</button>
        </div>
      </form>
    </div>
    <!-- /.card-body -->
  </div>
</section>
@include ('includes.script')
@endsection

resources/views/kriteria/kriteria.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">KRITERIA</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item active">Kriteria</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="card">
    <!-- /.card-header -->
    <div class="card-body">
      <table id="data-admin" class="table table-bordered table-striped">
        <thead>
        <tr>
          <th>NO</th>
          <th>KODE</th>
          <th>NAMA</th>
          <th>SUB KRITERIA</th>
          <th>AKSI</th>
        </tr>
        </thead>
        <tbody>
          @foreach($data as $krit)
        <tr>
          <td>{{$loop->iteration}}</td>
          <td>{{$krit->kode}}</td>
          <td>{{$krit->nama}}</td>
          <td>
            <a href="/sub_kriteria/{{$krit->kode}}">
              <span class="badge badge-secondary" data-toggle="tooltip" data-placement="top" title="Ubah">Lihat Sub Kriteria</span>
            </a>
          </td>
          <td>
            <a href="/kriteria/{{$krit->kode}}/edit">
              <span class="btn badge badge-secondary" data-toggle="tooltip" data-placement="top" title="Ubah"><i class="fa fa-pencil"></i></span>
            </a>                    
            <span class="btn badge badge-danger" onclick="event.preventDefault(); document.getElementById('delete-kriteria').submit();" data-toggle="tooltip" data-placement="top" title="Hapus"><i class="fa fa-trash"></i></span>
          </td>
          
          <form id="delete-kriteria" action="/kriteria/{{$krit->kode}}" method="post" style="display: none;">
            @method('DELETE')
            @csrf
          </form>
        </tr>
        @endforeach
        </tbody>
      </table>
    </div>
    <!-- /.card-body -->
  </div>
</section>
@include ('includes.script')
<script type="text/javascript">
$(document).ready(function(){
    // Append all paragraphs
    $("#data-admin_length").append('<a  href="{{ route('kriteria.create') }}"> <button type="button" class="btn btn-outline-primary ml-3">Tambah</button></a>');
});
</script>
@endsection

resources/views/kriteria/tambah_kriteria.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Kriteria</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item active">Kriteria</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="card">
    @if ($errors->any())
    <div class="alert alert-danger">
      <ul>
        @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
    @endif
    <!-- /.card-header -->
    <div class="card-body">
      <form role="form" method="post" action="{{ route('kriteria.store') }}">
        @csrf
        <div class="card-body">
          <div class="form-group">
            <label for="exampleInputEmail1">Kode Kriteria</label>
            <input type="text" class="form-control" name="kode" id="exampleInputEmail1" placeholder="kode">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Nama Kriteria</label>
            <input type="text" class="form-control" name="nama" id="exampleInputPassword1" placeholder="nama">
          </div>
        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>
    </div>
    <!-- /.card-body -->
  </div>
</section>
@include ('includes.script')
@endsection